# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/core" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/manual"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/story-painter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/verify"
    schedule:
      interval: "weekly"
