version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - gomodguard
    - goprintffuncname
    - gosec
    - intrange
    - loggercheck
    - makezero
    - mirror
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - sqlclosecheck
    - stylecheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 35
      package-average: 10.0
    revive:
      rules:
        - name: var-declaration
          disabled: true
    errcheck:
      check-type-assertions: false
      check-blank: false
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G404
        - G204
        - G110
        - G306
        - G101
        - G501
        - G505
        - G115
    exhaustruct:
      exclude:
        # std libs
        - "^net/http.Client$"
        - "^net/http.Cookie$"
        - "^net/http.Request$"
        - "^net/http.Response$"
        - "^net/http.Server$"
        - "^net/http.Transport$"
        - "^net/url.URL$"
        - "^os/exec.Cmd$"
        - "^reflect.StructField$"
        # public libs
        - "^github.com/Shopify/sarama.Config$"
        - "^github.com/Shopify/sarama.ProducerMessage$"
        - "^github.com/mitchellh/mapstructure.DecoderConfig$"
        - "^github.com/prometheus/client_golang/.+Opts$"
        - "^github.com/spf13/cobra.Command$"
        - "^github.com/spf13/cobra.CompletionOptions$"
        - "^github.com/stretchr/testify/mock.Mock$"
        - "^github.com/testcontainers/testcontainers-go.+Request$"
        - "^github.com/testcontainers/testcontainers-go.FromDockerfile$"
        - "^golang.org/x/tools/go/analysis.Analyzer$"
        - "^google.golang.org/protobuf/.+Options$"
        - "^gopkg.in/yaml.v3.Node$"
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: false
    nolintlint:
      allow-no-explanation: [ funlen, gocognit, lll ]
      require-explanation: false
      require-specific: false
      allow-unused: true
    perfsprint:
      strconcat: false
    sloglint:
      no-global: "default"
      context: "scope"
    forbidigo:
      exclude-godoc-examples: true
      analyze-types: true
  exclusions:
    rules:
      - source: "(noinspection|TODO)"
        linters: [godot]
      - source: "//noinspection"
        linters: [gocritic]
      - path: "_test\\.go"
        linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck

issues:
  max-same-issues: 50

run:
  timeout: 3m