# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
#    - go generate ./...
project_name: sealdice-core
builds:
  - id: sealdice-core-android-arm64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CGO_FLAGS=-Werror=unused-variable -Werror=implicit-function-declaration -O2 -H=windowsgui
      - CC=C:\Users\MSI-NB\AppData\Local\Android\Sdk\ndk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android28-clang
      - CXX=C:\Users\MSI-NB\AppData\Local\Android\Sdk\ndk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android28-clang++
    goos:
      - android
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    gcflags:
      - all="-l" # -B


  - id: sealdice-core-android-amd64
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CGO_FLAGS=-Werror=unused-variable -Werror=implicit-function-declaration -O2 -H=windowsgui
      - CC=C:\Users\MSI-NB\AppData\Local\Android\Sdk\ndk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\x86_64-linux-android28-clang
      - CXX=C:\Users\MSI-NB\AppData\Local\Android\Sdk\ndk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\x86_64-linux-android28-clang++
    goos:
      - android
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}}
    gcflags:
      - all="-l" # -B

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: data/helpdoc/COC
        dst: .
      - src: data/helpdoc/DND
        dst: .
      - src: data/names
        dst: .
      - src: data/decks/seal.json
        dst: .
      - src: temp/go-cqhttp_{{ .Os }}_{{ .Arch }}
        dst: go-cqhttp
        strip_parent: true
      - src: temp/lagrange_{{ .Os }}_{{ .Arch }}
        dst: lagrange
        strip_parent: true

checksum:
  name_template: 'checksums.txt'

snapshot:
#  name_template: "{{ incpatch }}"
  name_template: "{{ incpatch .Version }}"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
