// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PreviewBbs: typeof import('./components/previews/preview-bbs.vue')['default']
    PreviewBbsItem: typeof import('./components/previews/preview-bbs-item.vue')['default']
    PreviewMain: typeof import('./components/previews/preview-main.vue')['default']
    PreviewMainItem: typeof import('./components/previews/preview-main-item.vue')['default']
    PreviewTrg: typeof import('./components/previews/preview-trg.vue')['default']
    PreviewTrgItem: typeof import('./components/previews/preview-trg-item.vue')['default']
  }
}

export { }
