// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Nested: typeof import('./components/mod/nested.vue')['default']
    PageAbout: typeof import('./components/PageAbout.vue')['default']
    PageConnectInfoItems: typeof import('./components/PageConnectInfoItems.vue')['default']
    PageCustomReply: typeof import('./components/mod/PageCustomReply.vue')['default']
    PageCustomText: typeof import('./components/PageCustomText.vue')['default']
    PageJs: typeof import('./components/mod/PageJs.vue')['default']
    PageLog: typeof import('./components/PageLog.vue')['default']
    PageMisc: typeof import('./components/PageMisc.vue')['default']
    PageMiscBackup: typeof import('./components/misc/PageMiscBackup.vue')['default']
    PageMiscBanList: typeof import('./components/misc/PageMiscBanList.vue')['default']
    PageMiscDeck: typeof import('./components/mod/PageMiscDeck.vue')['default']
    PageMiscGroup: typeof import('./components/misc/PageMiscGroup.vue')['default']
    PageMiscSettings: typeof import('./components/misc/PageMiscSettings.vue')['default']
    PageMod: typeof import('./components/PageMod.vue')['default']
    PageTest: typeof import('./components/PageTest.vue')['default']
  }
}

export { }
