package main

// Code generated by peg -inline roll.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	rulee
	rulee1
	rulee2
	rulee3
	ruleeDice
	rulee4
	rulevalue
	rulenumber
	rulesub
	ruleadd
	ruleminus
	rulemultiply
	ruledivide
	rulemodulus
	ruleexponentiation
	ruleopen
	ruleclose
	rulesp
	ruleAction0
	ruleAction1
	ruleAction2
	ruleAction3
	ruleAction4
	ruleAction5
	ruleAction6
	ruleAction7
	ruleAction8
	ruleAction9
	rulePegText
)

var rul3s = [...]string{
	"Unknown",
	"e",
	"e1",
	"e2",
	"e3",
	"eDice",
	"e4",
	"value",
	"number",
	"sub",
	"add",
	"minus",
	"multiply",
	"divide",
	"modulus",
	"exponentiation",
	"open",
	"close",
	"sp",
	"Action0",
	"Action1",
	"Action2",
	"Action3",
	"Action4",
	"Action5",
	"Action6",
	"Action7",
	"Action8",
	"Action9",
	"PegText",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type DiceRollParser struct {
	RollExpression

	Buffer string
	buffer []rune
	rules  [30]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *DiceRollParser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *DiceRollParser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *DiceRollParser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *DiceRollParser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *DiceRollParser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *DiceRollParser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func (p *DiceRollParser) Execute() {
	buffer, _buffer, text, begin, end := p.Buffer, p.buffer, "", 0, 0
	for _, token := range p.Tokens() {
		switch token.pegRule {

		case rulePegText:
			begin, end = int(token.begin), int(token.end)
			text = string(_buffer[begin:end])

		case ruleAction0:
			p.AddOperator(TypeAdd)
			fmt.Println("!!!!!")
		case ruleAction1:
			p.AddOperator(TypeSubtract)
		case ruleAction2:
			p.AddOperator(TypeMultiply)
		case ruleAction3:
			p.AddOperator(TypeDivide)
		case ruleAction4:
			p.AddOperator(TypeModulus)
		case ruleAction5:
			p.AddOperator(TypeExponentiation)
		case ruleAction6:
			p.AddOperator(TypeDice)
		case ruleAction7:
			p.AddOperator(TypeDiceUnary)
		case ruleAction8:
			p.AddOperator(TypeNegation)
		case ruleAction9:
			p.AddValue(buffer[begin:end])

		}
	}
	_, _, _, _, _ = buffer, _buffer, text, begin, end
}

func Pretty(pretty bool) func(*DiceRollParser) error {
	return func(p *DiceRollParser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*DiceRollParser) error {
	return func(p *DiceRollParser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *DiceRollParser) Init(options ...func(*DiceRollParser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 e <- <(sp e1 !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[rulesp]() {
					goto l0
				}
				if !_rules[rulee1]() {
					goto l0
				}
				{
					position2, tokenIndex2 := position, tokenIndex
					if !matchDot() {
						goto l2
					}
					goto l0
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
				add(rulee, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 e1 <- <(e2 ((add e2 Action0) / (minus e2 Action1))*)> */
		func() bool {
			position3, tokenIndex3 := position, tokenIndex
			{
				position4 := position
				if !_rules[rulee2]() {
					goto l3
				}
			l5:
				{
					position6, tokenIndex6 := position, tokenIndex
					{
						position7, tokenIndex7 := position, tokenIndex
						{
							position9 := position
							if buffer[position] != rune('+') {
								goto l8
							}
							position++
							if !_rules[rulesp]() {
								goto l8
							}
							add(ruleadd, position9)
						}
						if !_rules[rulee2]() {
							goto l8
						}
						{
							add(ruleAction0, position)
						}
						goto l7
					l8:
						position, tokenIndex = position7, tokenIndex7
						if !_rules[ruleminus]() {
							goto l6
						}
						if !_rules[rulee2]() {
							goto l6
						}
						{
							add(ruleAction1, position)
						}
					}
				l7:
					goto l5
				l6:
					position, tokenIndex = position6, tokenIndex6
				}
				add(rulee1, position4)
			}
			return true
		l3:
			position, tokenIndex = position3, tokenIndex3
			return false
		},
		/* 2 e2 <- <(e3 ((multiply e3 Action2) / (divide e3 Action3) / (modulus e3 Action4))*)> */
		func() bool {
			position12, tokenIndex12 := position, tokenIndex
			{
				position13 := position
				if !_rules[rulee3]() {
					goto l12
				}
			l14:
				{
					position15, tokenIndex15 := position, tokenIndex
					{
						position16, tokenIndex16 := position, tokenIndex
						{
							position18 := position
							if buffer[position] != rune('*') {
								goto l17
							}
							position++
							if !_rules[rulesp]() {
								goto l17
							}
							add(rulemultiply, position18)
						}
						if !_rules[rulee3]() {
							goto l17
						}
						{
							add(ruleAction2, position)
						}
						goto l16
					l17:
						position, tokenIndex = position16, tokenIndex16
						{
							position21 := position
							if buffer[position] != rune('/') {
								goto l20
							}
							position++
							if !_rules[rulesp]() {
								goto l20
							}
							add(ruledivide, position21)
						}
						if !_rules[rulee3]() {
							goto l20
						}
						{
							add(ruleAction3, position)
						}
						goto l16
					l20:
						position, tokenIndex = position16, tokenIndex16
						{
							position23 := position
							if buffer[position] != rune('%') {
								goto l15
							}
							position++
							if !_rules[rulesp]() {
								goto l15
							}
							add(rulemodulus, position23)
						}
						if !_rules[rulee3]() {
							goto l15
						}
						{
							add(ruleAction4, position)
						}
					}
				l16:
					goto l14
				l15:
					position, tokenIndex = position15, tokenIndex15
				}
				add(rulee2, position13)
			}
			return true
		l12:
			position, tokenIndex = position12, tokenIndex12
			return false
		},
		/* 3 e3 <- <(eDice (exponentiation eDice Action5)*)> */
		func() bool {
			position25, tokenIndex25 := position, tokenIndex
			{
				position26 := position
				if !_rules[ruleeDice]() {
					goto l25
				}
			l27:
				{
					position28, tokenIndex28 := position, tokenIndex
					{
						position29 := position
						{
							position30, tokenIndex30 := position, tokenIndex
							if buffer[position] != rune('^') {
								goto l31
							}
							position++
							if !_rules[rulesp]() {
								goto l31
							}
							goto l30
						l31:
							position, tokenIndex = position30, tokenIndex30
							if buffer[position] != rune('*') {
								goto l28
							}
							position++
							if buffer[position] != rune('*') {
								goto l28
							}
							position++
							if !_rules[rulesp]() {
								goto l28
							}
						}
					l30:
						add(ruleexponentiation, position29)
					}
					if !_rules[ruleeDice]() {
						goto l28
					}
					{
						add(ruleAction5, position)
					}
					goto l27
				l28:
					position, tokenIndex = position28, tokenIndex28
				}
				add(rulee3, position26)
			}
			return true
		l25:
			position, tokenIndex = position25, tokenIndex25
			return false
		},
		/* 4 eDice <- <((e4 ('d' e4 ('k' e4)? Action6)*) / ('d' e4 ('k' e4)? Action7)*)> */
		func() bool {
			{
				position34 := position
				{
					position35, tokenIndex35 := position, tokenIndex
					if !_rules[rulee4]() {
						goto l36
					}
				l37:
					{
						position38, tokenIndex38 := position, tokenIndex
						if buffer[position] != rune('d') {
							goto l38
						}
						position++
						if !_rules[rulee4]() {
							goto l38
						}
						{
							position39, tokenIndex39 := position, tokenIndex
							if buffer[position] != rune('k') {
								goto l39
							}
							position++
							if !_rules[rulee4]() {
								goto l39
							}
							goto l40
						l39:
							position, tokenIndex = position39, tokenIndex39
						}
					l40:
						{
							add(ruleAction6, position)
						}
						goto l37
					l38:
						position, tokenIndex = position38, tokenIndex38
					}
					goto l35
				l36:
					position, tokenIndex = position35, tokenIndex35
				l42:
					{
						position43, tokenIndex43 := position, tokenIndex
						if buffer[position] != rune('d') {
							goto l43
						}
						position++
						if !_rules[rulee4]() {
							goto l43
						}
						{
							position44, tokenIndex44 := position, tokenIndex
							if buffer[position] != rune('k') {
								goto l44
							}
							position++
							if !_rules[rulee4]() {
								goto l44
							}
							goto l45
						l44:
							position, tokenIndex = position44, tokenIndex44
						}
					l45:
						{
							add(ruleAction7, position)
						}
						goto l42
					l43:
						position, tokenIndex = position43, tokenIndex43
					}
				}
			l35:
				add(ruleeDice, position34)
			}
			return true
		},
		/* 5 e4 <- <((minus value Action8) / value)> */
		func() bool {
			position47, tokenIndex47 := position, tokenIndex
			{
				position48 := position
				{
					position49, tokenIndex49 := position, tokenIndex
					if !_rules[ruleminus]() {
						goto l50
					}
					if !_rules[rulevalue]() {
						goto l50
					}
					{
						add(ruleAction8, position)
					}
					goto l49
				l50:
					position, tokenIndex = position49, tokenIndex49
					if !_rules[rulevalue]() {
						goto l47
					}
				}
			l49:
				add(rulee4, position48)
			}
			return true
		l47:
			position, tokenIndex = position47, tokenIndex47
			return false
		},
		/* 6 value <- <((number Action9) / sub)> */
		func() bool {
			position52, tokenIndex52 := position, tokenIndex
			{
				position53 := position
				{
					position54, tokenIndex54 := position, tokenIndex
					{
						position56 := position
						{
							position57 := position
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l55
							}
							position++
						l58:
							{
								position59, tokenIndex59 := position, tokenIndex
								if c := buffer[position]; c < rune('0') || c > rune('9') {
									goto l59
								}
								position++
								goto l58
							l59:
								position, tokenIndex = position59, tokenIndex59
							}
							add(rulePegText, position57)
						}
						if !_rules[rulesp]() {
							goto l55
						}
						add(rulenumber, position56)
					}
					{
						add(ruleAction9, position)
					}
					goto l54
				l55:
					position, tokenIndex = position54, tokenIndex54
					{
						position61 := position
						{
							position62 := position
							if buffer[position] != rune('(') {
								goto l52
							}
							position++
							if !_rules[rulesp]() {
								goto l52
							}
							add(ruleopen, position62)
						}
						if !_rules[rulee1]() {
							goto l52
						}
						{
							position63 := position
							if buffer[position] != rune(')') {
								goto l52
							}
							position++
							if !_rules[rulesp]() {
								goto l52
							}
							add(ruleclose, position63)
						}
						add(rulesub, position61)
					}
				}
			l54:
				add(rulevalue, position53)
			}
			return true
		l52:
			position, tokenIndex = position52, tokenIndex52
			return false
		},
		/* 7 number <- <(<[0-9]+> sp)> */
		nil,
		/* 8 sub <- <(open e1 close)> */
		nil,
		/* 9 add <- <('+' sp)> */
		nil,
		/* 10 minus <- <('-' sp)> */
		func() bool {
			position67, tokenIndex67 := position, tokenIndex
			{
				position68 := position
				if buffer[position] != rune('-') {
					goto l67
				}
				position++
				if !_rules[rulesp]() {
					goto l67
				}
				add(ruleminus, position68)
			}
			return true
		l67:
			position, tokenIndex = position67, tokenIndex67
			return false
		},
		/* 11 multiply <- <('*' sp)> */
		nil,
		/* 12 divide <- <('/' sp)> */
		nil,
		/* 13 modulus <- <('%' sp)> */
		nil,
		/* 14 exponentiation <- <(('^' sp) / ('*' '*' sp))> */
		nil,
		/* 15 open <- <('(' sp)> */
		nil,
		/* 16 close <- <(')' sp)> */
		nil,
		/* 17 sp <- <(' ' / '\t')*> */
		func() bool {
			{
				position76 := position
			l77:
				{
					position78, tokenIndex78 := position, tokenIndex
					{
						position79, tokenIndex79 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l80
						}
						position++
						goto l79
					l80:
						position, tokenIndex = position79, tokenIndex79
						if buffer[position] != rune('\t') {
							goto l78
						}
						position++
					}
				l79:
					goto l77
				l78:
					position, tokenIndex = position78, tokenIndex78
				}
				add(rulesp, position76)
			}
			return true
		},
		/* 19 Action0 <- <{ p.AddOperator(TypeAdd); fmt.Println("!!!!!"); }> */
		nil,
		/* 20 Action1 <- <{ p.AddOperator(TypeSubtract) }> */
		nil,
		/* 21 Action2 <- <{ p.AddOperator(TypeMultiply) }> */
		nil,
		/* 22 Action3 <- <{ p.AddOperator(TypeDivide) }> */
		nil,
		/* 23 Action4 <- <{ p.AddOperator(TypeModulus) }> */
		nil,
		/* 24 Action5 <- <{ p.AddOperator(TypeExponentiation) }> */
		nil,
		/* 25 Action6 <- <{ p.AddOperator(TypeDice) }> */
		nil,
		/* 26 Action7 <- <{ p.AddOperator(TypeDiceUnary) }> */
		nil,
		/* 27 Action8 <- <{ p.AddOperator(TypeNegation) }> */
		nil,
		/* 28 Action9 <- <{ p.AddValue(buffer[begin:end]) }> */
		nil,
		nil,
	}
	p.rules = _rules
	return nil
}
