name: PR Title Checker
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false

      - name: Add comment to fix PR title
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.check.outputs.success == 'false'}}
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### 🚨 PR Title Needs Formatting
              The title of this PR needs to be formatted correctly. 
              Please update the title to match the format `type: description`. Examples:
              - `fix: fix typo in README.md 
              - `chore: update dependencies`
              - `feat: add new feature`
              - `chore: fixing build pipeline`
              - etc.
              More information can be found [here](https://www.conventionalcommits.org/zh-hans/v1.0.0/).

      - name: Add comment that PR title is fixed
        if: ${{ steps.check.outputs.success == 'true'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'PR Title Check'
          recreate: true
          message: |
              ### ✅ PR Title Formatted Correctly
              The title of this PR matches the correct format.
