name: Review Dog

on:
  pull_request_target:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/reviewdog.yml'

jobs:
  review-dog:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: Review Dog
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go get
      - run: go generate ./...
      - name: Set Up GolangCI-Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run golangci-lint & reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golangci-lint run | reviewdog -reporter=github-pr-review -f=golangci-lint -filter-mode=nofilter -fail-on-error