name: Review Dog

on:
  pull_request_target:
    paths:
      - '**.go'
      - 'go.mod'

jobs:
  review-dog:
    name: Review Dog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref }}"
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - run: go get
      - run: go generate ./...

      - name: GolangCI-Lint with review-dog
        uses: reviewdog/action-golangci-lint@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tool_name: 'golangci-lint'
          reporter: 'github-pr-review'
          filter_mode: 'file'
          golangci_lint_version: 'v1.61.0'
          go_version: '1.22'
          cache: false